"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

import pymysql
from dotenv import load_dotenv

pymysql.install_as_MySQLdb()
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY: SECRET_KEY must be set via environment variable. No hardcoded fallback in production.
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    # Only allow an insecure fallback in local development (DEBUG=True).
    # In CI/production this will raise an error if SECRET_KEY is not set.
    _debug_flag = os.getenv('DEBUG', 'False') == 'True'
    if _debug_flag:
        SECRET_KEY = 'django-insecure-dev-only-key-change-in-production'  # nosec
    else:
        raise RuntimeError(
            "SECRET_KEY environment variable is required in non-debug mode. "
            "Please set it in your .env file or server environment."
        )

DEBUG = os.getenv('DEBUG', 'False') == 'True'

# SECURITY: ALLOWED_HOSTS must be explicitly set via env. Empty list causes 400 in production.
_ALLOWED_HOSTS_ENV = os.getenv('ALLOWED_HOSTS', '')
_parsed_hosts = [h.strip() for h in _ALLOWED_HOSTS_ENV.split(',') if h.strip()]
ALLOWED_HOSTS = _parsed_hosts if _parsed_hosts else (['*'] if DEBUG else [])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'legacy_people',
    'compressor',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'legacy_people.middleware.SecurityHeadersMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

_DB_ENGINE = os.getenv('DB_ENGINE', 'django.db.backends.mysql')
_USE_SQLITE = _DB_ENGINE == 'django.db.backends.sqlite3'

DATABASES = {
    'default': {
        'ENGINE': _DB_ENGINE,
        'NAME': BASE_DIR / 'db.sqlite3' if _USE_SQLITE else os.getenv('DB_NAME', 'legacypeople'),
        'USER': '' if _USE_SQLITE else os.getenv('DB_USER', 'django'),
        'PASSWORD': '' if _USE_SQLITE else os.getenv('DB_PASSWORD', 'django'),
        'HOST': '' if _USE_SQLITE else os.getenv('DB_HOST', '127.0.0.1'),
        'PORT': '' if _USE_SQLITE else os.getenv('DB_PORT', '3306'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Fortaleza'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
]

COMPRESS_PRECOMPILERS = (
    ('text/x-scss', 'npx sass {infile} {outfile}'),
)

LOGIN_URL = 'legacy_people:login'

# -------------------------------------------------------------------
# SECURITY HARDENING
# -------------------------------------------------------------------

# Session cookie: only sent over HTTPS in production
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True   # Prevent JS access to session cookie
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF mitigation for cross-site requests
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 3600        # 1 hour maximum session lifetime

# CSRF cookie hardening
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'

# Prevent browsers from guessing content type (MIME sniffing)
SECURE_CONTENT_TYPE_NOSNIFF = True

# Force HTTPS redirects in production (HTTP → HTTPS 301)
SECURE_SSL_REDIRECT = not DEBUG

# HTTP Strict Transport Security (HSTS) — 1 year in production
SECURE_HSTS_SECONDS = 0 if DEBUG else 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG

# Clickjacking protection (also handled by XFrameOptionsMiddleware)
X_FRAME_OPTIONS = 'DENY'

# Referrer-Policy
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# Reverse Proxy / Proxy SSL Header settings (H-02 mitigation)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
