# Generated by Django 4.2.30 on 2026-07-20 21:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Endereço de E-mail')),
                ('whatsapp', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='O número deve estar no formato: +5511999999999 (apenas números)', regex='^\\+55\\d{10,11}$')], verbose_name='Número de WhatsApp')),
                ('has_gc', models.BooleanField(default=False, verbose_name='Faz parte de um GC?')),
                ('gc_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Qual Grupo de Crescimento?')),
                ('time_lagoinha', models.CharField(max_length=100, verbose_name='Tempo em Lagoinha')),
                ('feeling', models.IntegerField(choices=[(1, 'Ótimo'), (2, 'Bem'), (3, 'Neutro'), (4, 'Não muito bem'), (5, 'Mal')], verbose_name='Como você está se sentindo?')),
                ('prayer_request', models.TextField(blank=True, verbose_name='Pedido de oração')),
                ('wants_chat', models.BooleanField(default=False, verbose_name='Gostaria de conversar?')),
                ('frequents_legacy', models.BooleanField(default=True, verbose_name='Frequenta o culto Legacy/programações?')),
                ('legacy_reason', models.TextField(blank=True, verbose_name='O que te faria se interessar mais?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': ['-created_at'],
            },
        ),
    ]
