# Generated by Django 4.2.30 on 2026-10-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy_people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='legacy_reason',
            field=models.TextField(blank=True, max_length=2000, verbose_name='O que te faria se interessar mais?'),
        ),
        migrations.AlterField(
            model_name='person',
            name='prayer_request',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Pedido de oração'),
        ),
        migrations.AlterField(
            model_name='person',
            name='time_lagoinha',
            field=models.CharField(choices=[('menos_6_meses', 'Menos de 6 meses'), ('6_meses_1_ano', 'Entre 6 meses e 1 ano'), ('1_3_anos', 'Entre 1 e 3 anos'), ('mais_3_anos', 'Mais de 3 anos')], max_length=50, verbose_name='Tempo em Lagoinha'),
        ),
    ]
