# Generated by Django 4.2.30 on 2026-10-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy_people', '0002_alter_person_legacy_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimit',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
